services:
  backend:
    image: ghcr.io/upikoth/starter-bun
    container_name: backend
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      APP_NAME: ${APP_NAME}
      FRONT_URL: ${FRONT_URL}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
    volumes:
      - type: bind
        source: /var/www/databases/starter-bun-database.sqlite
        target: /home/bun/app/database.sqlite
      - type: bind
        source: /var/www/logs/starter-bun
        target: /home/bun/app/logs
