openapi: 3.1.0
info:
  title: Starter API
  version: 1.0.0

servers:
  - url: http://localhost:8000/
    description: Dev server
  - url: https://starter.upikoth.dev/
    description: Production server

externalDocs:
  description: Документация по проекту starter
  url: https://upikoth.dev/projects/starter/intro.html

tags:
  - name: health
    description: Проверка работоспособности приложения
  - name: sessions
    description: CRUD методы для сессии

paths:
  /api/v1/health:
    get:
      tags:
        - health
      description: Проверка работоспособности приложения
      responses:
        200:
          description: Приложение работает
          $ref: '#/components/responses/defaultSuccess'

  /api/v1/session:
    get:
      tags:
        - sessions
      description: Получение информации о текущей сессии пользователя
      security:
        - authorization: []
      responses:
        200:
          description: Информация о текущей сессии пользователя
          $ref: '#/components/responses/sessionsGetCurrentSessionSuccess'
        401:
          description: Пользователь не авторизован
          $ref: '#/components/responses/defaultNotAuthorized'

  /api/v1/sessions:
    get:
      tags:
        - sessions
      description: Получение информации обо всех сессиях в приложении

      parameters:
        - $ref: '#/components/parameters/limitParameter'
        - $ref: '#/components/parameters/offsetParameter'

      responses:
        200:
          description: Список всех сессий
          $ref: '#/components/responses/sessionsGetAllSessionSuccessResponse'
        401:
          description: Пользователь не авторизован
          $ref: '#/components/responses/defaultNotAuthorized'
        403:
          description: Недостаточно прав
          $ref: '#/components/responses/defaultForbidden'

    post:
      tags:
        - sessions
      description: Создание сессии пользователя по логину и паролю
      requestBody:
        $ref: '#/components/requestBodies/sessionsCreateSessionBodyRequest'

      responses:
        200:
          description: Сессия успешно создана
          $ref: '#/components/responses/sessionsCreateSessionSuccessResponse'
        400:
          description: Переданы некорректные логин или пароль
          $ref: '#/components/responses/sessionsCreateSessionWrongData'

components:
  schemas:
    user:
      type: object
      required:
        - id
        - email
        - status
        - role
      properties:
        id:
          type: integer
        email:
          type: string
          format: email
        status:
          type: string
          enum:
            - active
            - blocked
        role :
          type: string
          enum:
            - user
            - admin
            - super-admin

    defaultSuccessResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object

    defaultNotAuthorizedResponse:
      type: object
      required:
        - success
        - data
        - error
      properties: 
        success:
          type: boolean
          enum:
            - false
        data:
          type: object
        error:
          type: object
          required:
            - code
            - description
          properties:
            code:
              type: integer
              enum:
                - 9
            description:
              type: string
              enum:
                - Пользователь не авторизован

    defaultForbiddenResponse:
      type: object
      required:
        - success
        - data
        - error
      properties: 
        success:
          type: boolean
          enum:
            - false
        data:
          type: object
        error:
          type: object
          required:
            - code
            - description
          properties:
            code:
              type: integer
              enum:
                - 10
            description:
              type: string
              enum:
                - Недостаточно прав

    sessionsGetCurrentSessionSuccessResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object
          required:
            - user
            - session
          properties:
            user:
              $ref: '#/components/schemas/user'
            session:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer

    sessionsGetAllSessionSuccessResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object
          required:
            - sessions
            - limit
            - offset
            - total
          properties:
            sessions:
              type: array
              items:
                type: object
                required:
                  - id
                  - userId
                properties:
                  id:
                    type: integer
                  userId:
                    type: integer
            limit:
              type: integer
            offset:
              type: integer
            total:
              type: integer

    sessionsCreateSessionBodyRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    sessionsCreateSessionSuccessResponse:
      type: object
      required:
        - success
        - data
      properties: 
        success:
          type: boolean
          enum:
            - true
        data:
          type: object
          required:
            - user
            - session
          properties:
            user:
              $ref: '#/components/schemas/user'
            session:
              type: object
              required:
                - id
              properties:
                id:
                  type: integer

    sessionsCreateSessionWrongDataResponse:
      type: object
      required:
        - success
        - data
        - error
      properties: 
        success:
          type: boolean
          enum:
            - false
        data:
          type: object
        error:
          type: object
          required:
            - code
            - description
          properties:
            code:
              type: integer
              enum:
                - 6
            description:
              type: string
              enum:
                - Email или пароль указаны неверно

  parameters:
    limitParameter:
      description: Максимальное количество элементов в ответе
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 0
        default: 10

    offsetParameter:
      description: Отступ, начиная с которого нужно возвращать элементы
      in: query
      name: offset
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0

  requestBodies:
    sessionsCreateSessionBodyRequest:
      description: Логин и пароль для входа в приложение
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sessionsCreateSessionBodyRequest'
          examples:
            emailAndPassword:
              summary: Логин и пароль
              externalValue: /api/docs/examples/sessions/create/request-email-password.json

  responses:
    defaultSuccess:
      description: Стандартный ответ при успешно выполенном запросе
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultSuccessResponse'
          examples:
            defaultSuccess:
              summary: Успешный ответ без доп. информации
              externalValue: /api/docs/examples/default/200.json

    defaultNotAuthorized:
      description: Пользователь не авторизован
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultNotAuthorizedResponse'
          examples:
            defaultNotAuthorized:
              summary: Ошибка авторизации
              externalValue: /api/docs/examples/default/401.json

    defaultForbidden:
      description: Недостаточно прав
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/defaultForbiddenResponse'
          examples:
            defaultForbidden:
              summary: Недостаточно прав
              externalValue: /api/docs/examples/default/403.json

    sessionsGetCurrentSessionSuccess:
      description: Успешное получение информации о сессии пользователя
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sessionsGetCurrentSessionSuccessResponse'
          examples:
            activeUser:
              summary: Активный пользователь
              externalValue: /api/docs/examples/sessions/get-current-session/response-success.json

    sessionsGetAllSessionSuccessResponse:
      description: Успешное получение списка сессий
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sessionsGetAllSessionSuccessResponse'
          examples:
            success:
              summary: Список сессий пользователей
              externalValue: /api/docs/examples/sessions/get-all/response-success.json

    sessionsCreateSessionSuccessResponse:
      description: Успешное создание сессии пользователя
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sessionsCreateSessionSuccessResponse'
          examples:
            success:
              summary: Данные о пользователе
              externalValue: /api/docs/examples/sessions/create/response-success.json

    sessionsCreateSessionWrongData:
      description: Ошибка при создании сессии
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/sessionsCreateSessionWrongDataResponse'
          examples:
            success:
              summary: Некорректные логин или пароль
              externalValue: /api/docs/examples/sessions/create/response-wrong-data.json

  securitySchemes:
    authorization:
      description:
        Для авторизации нужно вызвать POST метод /api/v1/sessions, передав корректные email и пароль, после чего
        токен установится в куки и будет передаваться во все методы при последующих вызовах

        Для удаления сессии нужно вызвать DELETE метод /api/v1/sessions, после чего куки удалятся

        Авторизация через поле ниже работать не будет из-за политик безопасности браузера
      name: Authorization
      type: apiKey
      in: cookie

security:
  - authorization: []
